[package]
name = "toolcenter-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "toolcenter_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true
windows.workspace = true
windows-core.workspace = true
