// This file is generated by pnpm registry:generate. Do not edit by hand.
import type { PluginDefinition } from "@tool-center/plugin-contract";
import plugin0 from "../../../plugins/audio-device-switcher/plugin.manifest";
import plugin1 from "../../../plugins/hdr-toggle/plugin.manifest";

export const pluginRegistry: readonly PluginDefinition[] = [plugin0, plugin1];
