// This file is generated by pnpm registry:generate. Do not edit by hand.
import type { PluginDefinition } from "@tool-center/plugin-contract";
import plugin0 from "../../../plugins/audio-device-switcher/plugin.manifest";
import plugin1 from "../../../plugins/flclash-controller/plugin.manifest";
import plugin2 from "../../../plugins/hdr-toggle/plugin.manifest";
import plugin3 from "../../../plugins/market-watch/plugin.manifest";
import plugin4 from "../../../plugins/pomodoro-timer/plugin.manifest";
import plugin5 from "../../../plugins/sticky-notes/plugin.manifest";

export const pluginRegistry: readonly PluginDefinition[] = [plugin0, plugin1, plugin2, plugin3, plugin4, plugin5];
