import { writeFile } from "node:fs/promises";
import path from "node:path";

import { discoverPlugins, loadManifest, toPosixPath } from "../../shared/plugins";

const workspaceRoot = process.cwd();
const outputPath = path.join(
  workspaceRoot,
  "apps",
  "desktop",
  "src",
  "plugin-registry.generated.ts",
);

const plugins = await discoverPlugins(workspaceRoot);
const ids = new Set<string>();
const imports: string[] = [];
const symbols: string[] = [];

for (const [index, plugin] of plugins.entries()) {
  const manifest = await loadManifest(plugin.manifestPath);
  if (ids.has(manifest.id)) {
    throw new Error(`Duplicate plugin id "${manifest.id}".`);
  }
  ids.add(manifest.id);

  const symbol = `plugin${index}`;
  const relativePath = toPosixPath(path.relative(path.dirname(outputPath), plugin.manifestPath))
    .replace(/\.ts$/, "")
    .replace(/^(?!\.)/, "./");
  imports.push(`import ${symbol} from ${JSON.stringify(relativePath)};`);
  symbols.push(symbol);
}

const contents = `${[
  "// This file is generated by pnpm registry:generate. Do not edit by hand.",
  'import type { PluginDefinition } from "@tool-center/plugin-contract";',
  ...imports,
  "",
  `export const pluginRegistry: readonly PluginDefinition[] = [${symbols.join(", ")}];`,
  "",
].join("\n")}`;

await writeFile(outputPath, contents, "utf8");
console.log(`Generated registry with ${plugins.length} plugin(s).`);

